<?php

$calls = [
    array(
        "call code" => 187,
        "caller id" => "546791",
        "operator id" => "35213",
        "date" => "Oct 3 2016",
        "time" => "09:45",
        "reason" => "Report new problem",
        "problem" => 325,
        "notes" => "",
    ),
    array(
        "call code" => 423,
        "caller id" => "534231",
        "operator id" => "5434",
        "date" => "Nov 12 2016",
        "time" => "12:34",
        "reason" => "Discuss existing problem",
        "problem" => 122,
        "notes" => "",
    ),
    array(
        "call code" => 453,
        "caller id" => "432153",
        "operator id" => "35213",
        "date" => "Oct 11 2016",
        "time" => "15:50",
        "reason" => "Discuss existing problem",
        "problem" => 144,
        "notes" => "",
    ),
    array(
        "call code" => 454,
        "caller id" => "456493",
        "operator id" => "35213",
        "date" => "Oct 12 2016",
        "time" => "10:50",
        "reason" => "Discuss existing problem",
        "problem" => 144,
        "notes" => "",
    )

];

$problems = [
    array(
        "problemNumber" => 328,
        "description" => "Concerned about the strength of the firewall. In particular
wants to keep out illegal messages from Mexico",
        "type" => "Network",
        "specialist" => "Nick",
        "date" => "Oct 4 2016, 4.15am",
        "callCode" => "190",
        "open" => false,
        "problem-priority" => "High",
        "problem-type" => "Network - Security Breach",
        "status" => 2
    ),
    array(
        "problemNumber" => 327,
        "description" => "Tendency to eject CDs early",
        "type" => "Hardware",
        "specialist" => "Bert",
        "date" => "Oct 4 2016, 9.20am",
        "callCode" => "189",
        "open" => true,
        "problem-priority" => "Low",
        "problem-type" => "Hardware - Laptop Computer",
        "status" => 2
    ),
    array(
        "problemNumber" => 326,
        "description" => "Email may have been hacked when using an external
        server",
        "type" => "Software",
        "specialist" => "James J",
        "date" => "Oct 3 2016, 9.15am",
        "callCode" => "188",
        "open" => true,
        "problem-priority" => "High",
        "problem-type" => "Network - Security Breach",
        "status" => 1
    ),
    array(
        "problemNumber" => 325,
        "description" => "Laptop running very slowly",
        "type" => "Hardware",
        "specialist" => "Clara",
        "date" => "Oct 3 2016, 9.00am",
        "callCode" => "187",
        "open" => false,
        "problem-priority" => "Low",
        "problem-type" => "Hardware - Laptop Computer",
        "status" => 1
    )
];

$personnel = array(
    array(
        "id" => 173483,
        "first_name" => "John",
        "last_name" => "Smith",
        "phone_number" => "012 3456 789",
        "email_address" => "JohnSmith@makeitall.com",
        "job_title" => "CTO",
        "department" => "Technology",
        "branch_location" => "London",
        "branch_country" => "UK",
        "branch_postcode" => "W1 1AA",
        "user_role" => "Admin",
        "availability" => "active"),
    array(
        "id" => 872446,
        "first_name" => "Jane",
        "last_name" => "Doe",
        "phone_number" => "687 2046 245",
        "email_address" => "JaneDoe@makeitall.com",
        "job_title" => "Operator",
        "department" => "Operations",
        "branch_location" => "Perth",
        "branch_country" => "AU",
        "branch_postcode" => "6000",
        "user_role" => "Operator",
        "availability" => "inactive"),
    array(
        "id" => 323543,
        "first_name" => "James",
        "last_name" => "Gold",
        "phone_number" => "874 6585 312",
        "email_address" => "JamesGold@makeitall.com",
        "job_title" => "Office Hardware Specialist",
        "department" => "Technology",
        "branch_location" => "New York",
        "branch_country" => "US",
        "branch_postcode" => "10001",
        "user_role" => "Specialist",
        "availability" => "unavailable"),
    array(
        "id" => 767645,
        "first_name" => "Sally",
        "last_name" => "Brown",
        "phone_number" => "878 6268 745",
        "email_address" => "SallyBrown@makeitall.com",
        "job_title" => "Senior Data Analyst",
        "department" => "Data",
        "branch_location" => "New York",
        "branch_country" => "US",
        "branch_postcode" => "10001",
        "user_role" => "Analyst",
        "availability" => "active"),
    array(
        "id" => 578415,
        "first_name" => "Max",
        "last_name" => "Henry",
        "job_title" => "Electrical Engineer",
        "department" => "Maintenance",
        "phone_number" => "020 4521 3216",
        "branch_location" => "Charleston SC",
        "branch_country" => "US",
        "branch_postcode" => "29401",
        "email_address" => "maxhenry@makeitall.com",
        "user_role" => "Specialist",
        "type" => "Hardware",
        "availability" => "active"),
    array(
        "id" => 657911,
        "first_name" => "Jane",
        "last_name" => "Smith",
        "job_title" => "Software Tester",
        "department" => "Research and Development",
        "phone_number" => "020 5496 6652",
        "branch_location" => "Green Bay WI",
        "branch_country" => "USA",
        "branch_postcode" => "54162",
        "email_address" => "janesmith@makeitall.com",
        "user_role" => "Specialist",
        "type" => "Software",
        "availability" => "unavailable"),
    array(
        "id" => 321564,
        "first_name" => "Sam",
        "last_name" => "Jones",
        "job_title" => "Technical Specialist",
        "department" => "Helpdesk",
        "phone_number" => "020 1325 4762",
        "branch_location" => "Tokyo",
        "branch_country" => "Japan",
        "branch_postcode" => "100-0014",
        "email_address" => "samjones@makeitall.com",
        "user_role" => "Specialist",
        "type" => "Network",
        "availability" => "active"),
    array(
        "id" => 641547,
        "first_name" => "James",
        "last_name" => "Johnson",
        "job_title" => "Helpdesk Operator",
        "department" => "Helpdesk",
        "phone_number" => "020 1325 4762",
        "branch_location" => "London",
        "branch_country" => "UK",
        "branch_postcode" => "RE11 3U4",
        "email_address" => "jamesjohnson@makeitall.com",
        "user_role" => "Operator",
        "availability" => "active")
    );

$software = [
    array(
        "serial number" => 215,
        "type" => "Operating System",
        "make" => "Microsoft",
        "model" => "Windows 10",
        "version" => 3.4,
        "license start" => "05-08-2018",
        "license end" => "05-08-2023",
        "in-house" => false,
    ),

    array(
        "serial number" => 157,
        "type" => "Word Processor",
        "make" => "Microsoft",
        "model" => "Word",
        "version" => 2.3,
        "license start" => "10-07-2019",
        "license end" => "10-07-2025",
        "in-house" => false,
    ),

    array(
        "serial number" => 267,
        "type" => "Photo Editing",
        "make" => "Adobe",
        "model" => "Photoshop",
        "version" => 9.5,
        "license start" => "06-06-2020",
        "license end" => "06-06-2024",
        "in-house" => false,
    ),
];


$hardware = [
    array(
        "serial number" => 155,
        "type" => "Printer",
        "make" => "HP",
        "model" => "HU125312",
        "version" => 2,
        "warranty start" => "04-02-2018",
        "warranty end" => "04-02-2020",
    ),
    array(
        "serial number" => 123,
        "type" => "Scanner",
        "make" => "Epson",
        "model" => "V600",
        "version" => 1,
        "warranty start" => "03-04-2017",
        "warranty end" => "03-04-2018",
    ),
    array(
        "serial number" => 641,
        "type" => "Headset",
        "make" => "Mpow",
        "model" => "DH1874",
        "version" => 3,
        "warranty start" => "01-05-2020",
        "warranty end" => "01-05-2021",
    ),
];
